### PR TITLE
Feature/database interfaces

### PR DESCRIPTION
**Pull request by Michalski-Artur**
Add interface (IOfferService) and its implementation OfferService. Offer service has such methods:
- AddOffer - ! no rooms adding is included
- DeleteOffer
- GetHotelOffer
- GetOffer
- UpdateOffer

Add models for endpoints (Offer.cs and OfferPreview.cs) - DTO classes
Renamed database models in following manner: Offer ->OfferDb
Right now  conversion from DTO to Db model and vice versa is through constructors. Currently working to use for this purpose AutoMapper

### CODE REVIEW

**Review by cangi75 — COMMENTED** [review]
i would change update funcion in IOfferService to
bool UpdateOffer(Offer)
this will be easier to use since we will pares json anyway

**Comment by Michalski-Artur** [comment]
I am not quite sure wether its good approach. Endpoint for updating offers looks like this:
image
And for me creating offer type object from such properties is a bit useless and may only lead to misunderstanding what properties we are actually changing through updating offer.

**Review by cangi75 — APPROVED** [review]
you are right.
I don't have any more objections to the code

**Comment by Michalski-Artur** [comment]
Also there is an issue as I look at all functions. I quess we should somehow differentiate whether offer is simply not found or hotel requesting changes is not its owner. Boolean type is not enough for this. Returning status codes may be a good solution, but its a bit strange that database interface return http status codes. What is your opinion?

**Comment by cangi75** [comment]
I think you can change every metod to void and assume tat it work. Then every problem (like offer not fund and not autohorizte) will be handle by exeptions, but i think that is not necessary. So it is your decison.

**Review by cangi75 — APPROVED** [review]
I assumed that hotelID will be added after receiving a massage.
I think that adding comments with information about exceptions next to functions that can throw them is a good idea, because there is no information about that in spec.

**Pull request closed without merging**
