### PR TITLE
Add ClientService & ClientDataAccess tests

### LINKED ISSUE #8: Umożliwienie zarządzania danymi konta klienta
Underestimated twice (took around 10 hours)

### PR DESCRIPTION
**Pull request by cyaneko**
Closes #8.

### CODE REVIEW

**Comment by Michalski-Artur** [comment]
From what i can see you only deleted PowerOfTests. Quess this is not point of this pull request @cyaneko

**Comment by cyaneko** [comment]
> From what i can see you only deleted PowerOfTests. Quess this is not point of this pull request @cyaneko

Apparently git doesn't like me for some reason; re-pushing

**Review by Michalski-Artur — APPROVED** [review]
Its rather little thing. I would only separate Arrange from Act in ClientServiceTest. Despite this everything fine 👍

**Comment by cyaneko** [comment]
> Its rather little thing. I would only separate Arrange from Act in ClientServiceTest. Despite this everything fine 👍

I'll fix this sometime in the evening then merge

**Pull request merged**
